DROP GBOARD;

CREATE TABLE GBOARD (
	GNO NUMBER PRIMARY KEY,
	GID VARCHAR2(32),
	GTITLE VARCHAR2(32),
	GCONTENT VARCHAR2(32),
	POSTDATE DATE,
	LASTUPDATE DATE,
	GIP VARCHAR2(32),
	GHIT NUMBER

);

DROP SEQUENCE GBOARD_SEQ;
CREATE SEQUENCE GBOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

