DROP TABLE GBOARD;

CREATE TABLE GBOARD (
	GNO NUMBER PRIMARY KEY,
	GID VARCHAR2(32),
	GTITLE VARCHAR2(32),
	GCONTENT VARCHAR2(32),
	FILENAME VARCHAR2(300),
	GHIT NUMBER,
	POSTDATE DATE,
	LASTUPDATE DATE
);

DROP SEQUENCE GBOARD_SEQ;
CREATE SEQUENCE GBOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

INSERT INTO GBOARD VALUES(GBOARD_SEQ.NEXTVAL,'test','test','content','filename',0,SYSDATE,SYSDATE);
INSERT INTO GBOARD VALUES(GBOARD_SEQ.NEXTVAL,'qwer1234','test','content','filename',0,SYSDATE,SYSDATE);
select * from gboard;