DROP TABLE GBOARD;

CREATE TABLE GBOARD (
	GNO NUMBER PRIMARY KEY,
	GID VARCHAR2(32),
	GTITLE VARCHAR2(32),
	GCONTENT VARCHAR2(32),
	FILENAME VARCHAR2(300),
	GHIT NUMBER,
	POSTDATE DATE,
	LASTUPDATE DATE
);

DROP SEQUENCE GBOARD_SEQ;
CREATE SEQUENCE GBOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

INSERT INTO GBOARD VALUES(GBOARD_SEQ.NEXTVAL,'test','test','content','filename',0,SYSDATE,SYSDATE);
INSERT INTO GBOARD VALUES(GBOARD_SEQ.NEXTVAL,'qwer1234','test','content','filename',0,SYSDATE,SYSDATE);
select * from gboard;

DROP TABLE GREPLY;
CREATE TABLE GREPLY(
	GNO NUMBER PRIMARY KEY,
	GID VARCHAR2(32),
	GBOARD_NO NUMBER,
	GCONTENT VARCHAR2(32),
	POSTDATE DATE,
	IP VARCHAR2(32)

	
);
DROP SEQUENCE GREPLY_SEQ;
CREATE SEQUENCE GREPLY_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
ALTER TABLE GREPLY ADD CONSTRAINT REPLY_BOARD_FK FOREIGN KEY(GBOARD_NO) REFERENCES GBOARD(GNO);
INSERT INTO GREPLY VALUES(GBOARD_SEQ.NEXTVAL,'qwer1234','3','dd',SYSDATE,'127.0.0.1');
select * from greply;
